### ISSUE TITLE
Unable to use arduino libraries installed by library manager

### ISSUE THREAD

**Issue by machadolab** [arduino-cmake/Arduino-CMake-NG#15]
I have tried both the **Built-in/Arduino Libraries** way and **User/3rd Party Libraries** way (as per the wiki documentation) to try and use a library that is installed with the Arduino IDE library manager. 

The first way does not work because it looks like Arduino-CMake-NG only searches the main Arduino libraries that come with the IDE software and not the user installed libraries that are installed into the **Sketchbook location** using the library manager.

**Comment by MrPointer** [comment]
Hello @machadolab, and yet again welcome abroad!
You said that our framework doesn't search the **Sketchbook location**, and you're indeed correct.
I'll check this out, and see if there's anything I can extract from the SDK's metadata to add this location to our search paths.
However , from my understanding it's something that's tightly bound to **Arduino IDE**'s **Library Manager**, which our framework knows nothing about - Which would make it impossible to know a user's **Sketchbook location**.
If indeed that's the case, one would have no other choice but to manually pass this location to the framework - That is something that we can easily take care of.

Regarding the issue you've come across with 3rd party libraries - Could you please submit a new, separate issue for this? It would be easier for us to maintain.

**Comment by machadolab** [comment]
So the issue is, since arduino libs need the same build flags as a 'built in' library, but the sketchbook location is not searched, there seems no way to build a project that uses these libs.

I suppose I could reverse engineer all the flags needed and simply treat it as a 'user library' but this seems way complicated since the library-manager installed libraries are basically exactly like the built in libs, just in a different location.

So I would suggest if you cant auto detect the sketchbook location, have a cmake parameter for them to specify the sketchbook location.

You should be able to easily reproduce this trouble by creating a very simple project using a Adafruit_NeoPixel example, for instance. You might also run into the same library naming issue I had too =)

**Comment by MrPointer** [comment]
@machadolab I think we misunderstood each other partly 😃 
What I've meant is that you'd open a new issue for the bug regarding **Adafruit_NeoPixel**, since a failure to build this library (as well as all other "user" libraries) has nothing to do with the **Sketchbook Location**.
I'm saying this since I already have fixes for both, but the fixes resolve different issues, so it'd be nicer to have them managed as separate issues on GitHub as well.

However, I'll do this myself now to spare some time and just in case you still don't understand my intentions. Meanwhile, I'll also edit parts of this issue to attribute it solely to the **Sketchbook Location** "bug".
